website/users/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, current_app
from website import database, bcrypt
from website.users.forms import RegistrationForm, LoginForm, RequestResetForm, ResetPasswordForm
from website.models import User
from flask_login import login_user, current_user, logout_user
from website.users.forms import UpdateAccountForm
from website.users.utils import save_picture, send_reset_email
from flask_login import login_user, current_user, logout_user, login_required


users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        with current_app.app_context():
            database.create_all()
            user = User(username=form.username.data, email = form.email.data, password=hashed_password)
            database.session.add(user)
            database.session.commit()

        flash(f"Your account has been created!", 'success')
        next_page = request.args.get('next')
        return redirect(url_for('users.login', next=next_page)) if next_page else redirect(url_for('users.login'))

    return render_template('register.html', title='Register', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    if form.validate_on_submit():
        with current_app.app_context():
            database.create_all()
            user= User.query.filter_by(email=form.email.data).first()
            if user and bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user, remember=form.remember.data)
                next_page= request.args.get('next')

                return redirect(next_page) if next_page else redirect(url_for('main.home'))
            else:
                flash('Login Unsuccessful. Please check email and password', 'danger')

    return render_template('login.html', title='Login', form=form)

@users.route('/logout')
def logout():
    logout_user()
    next_page= request.args.get('next')
    return redirect(next_page) if next_page else redirect(url_for('main.home'))

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file= picture_file
        current_user.username = form.username.data
        database.session.commit()
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='images/users/profile_pics/' + current_user.image_file)

    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home')) 
    form = RequestResetForm()
    if form.validate_on_submit():
        user= User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login')) 
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token): 
    if current_user.is_authenticated:
        return redirect(url_for('main.home')) 
    user= User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request')) 
    form= ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        print("new-------", hashed_password)
        print("old-------", user.password)
        user.password = hashed_password
        database.session.commit()
        flash(f"Your password has been updated and you can now log in!", 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

website/templates/footer.html
<footer>
    <p style="margin-right: 2px" >© 2024</p>
    <p style="margin-left: 2px" >John Pullmann</p>
</footer>

website/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="I'm Ján Pullmann, welcome to my personal website. Here you can find more about me, my skills and hobbies.">
    <meta name="keywords" content="Ján Pullmann John Pullmann Personal Website"/>
    <!-- icon -->
    <link rel="icon"  type="image/x-icon" href="{{ url_for('static', filename='images/icon.ico') }}">
    <!--link styling-->
    <link type="text/css" rel="stylesheet"  href="{{ url_for('static', filename='css/normalize.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

    <title>{{ title }}</title>
    <meta property="og:title" content="{{ title }} - Ján Pullmann Personal Website">
    <meta property="og:description" content="I'm Ján Pullmann, welcome to my personal website. Here you can find more about me, my skills and hobbies.">
    <meta property="og:image" content="{{ url_for('static', filename='images/icon.ico', _external=True) }}">
    <meta property="og:url" content="http://www.johnpullmann.com">
    <meta property="og:type" content="website">
</head>
<body class="{{ theme }}">

    <div class="container">
        {% include "nav.html" %}
        
        <div class="content {{ 'logged-in-content' if current_user.is_authenticated }}">
            <div class="sec-nav-pos-holder {{ 'logged-in-pos-holder' if current_user.is_authenticated }}"></div>

            {% block content %}
            {% endblock content %}

            {% include "footer.html" %}
        </div>

        {% include "scripts.html" %}
    </div>
    
</body>
</html>

website/templates/login.html
{% extends "layout.html" %}

{% block content %}

<div class="section section-form" id="login" style="padding-top: 15px;">
    <h2 class="section-title" style="margin-bottom: 15px; font-size: 30px;">Log in</h2> <!-- TODO change from intag styling to main.css-->
    <form id="form" class="general-form" method="POST">
        <div class="form-field" style="position:relative;">
            <!-- email input -->
            <div>
                {% if form.email.errors %}
                    {{ form.email(id="email",  class="input is-invalid",  placeholder="Email", pattern="[^@]+@[^@]+\.[a-zA-Z]{2,6}") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(id="email",  class="input",  placeholder="Email", pattern="[^@]+@[^@]+\.[a-zA-Z]{2,6}") }}
                {% endif %} 

                <label for="email">
                    <svg width="23" height="22" viewBox="0 0 23 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M1.91667 22C1.91667 22 0 22 0 20.1667C0 18.3333 1.91667 12.8333 11.5 12.8333C21.0833 12.8333 23 18.3333 23 20.1667C23 22 21.0833 22 21.0833 22H1.91667ZM11.5 11C13.025 11 14.4875 10.4205 15.5659 9.38909C16.6442 8.35764 17.25 6.95869 17.25 5.5C17.25 4.04131 16.6442 2.64236 15.5659 1.61091C14.4875 0.579463 13.025 0 11.5 0C9.97501 0 8.51247 0.579463 7.43414 1.61091C6.3558 2.64236 5.75 4.04131 5.75 5.5C5.75 6.95869 6.3558 8.35764 7.43414 9.38909C8.51247 10.4205 9.97501 11 11.5 11Z"/>
                    </svg>   
                        
                </label>
            </div>
        </div>
        <div class="form-field" style="position:relative; margin-bottom:10px;">
            <!-- password input -->
            <div>
                {% if form.password.errors %}
                    {{ form.password(id='password', class='input is-invalid', placeholder='Password', required='') }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(id='password', class='input', placeholder='Password', required='') }}
                {% endif %} 
                <label for="password">

                    <svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <g clip-path="url(#clip0_294_906)"><path d="M4.33325 22H17.6666C18.2189 22 18.6666 21.5523 18.6666 21V9.66667C18.6666 9.1144 18.2189 8.66667 17.6666 8.66667H16.6666V5.66667C16.6666 2.54207 14.1245 0 10.9999 0C7.87532 0 5.33325 2.54207 5.33325 5.66667V8.66667H4.33325C3.78099 8.66667 3.33325 9.1144 3.33325 9.66667V21C3.33325 21.5523 3.78099 22 4.33325 22ZM11.9999 15.6657V17C11.9999 17.5523 11.5522 18 10.9999 18C10.4477 18 9.99992 17.5523 9.99992 17V15.6657C9.59539 15.3614 9.33325 14.8775 9.33325 14.3333C9.33325 13.4143 10.0809 12.6667 10.9999 12.6667C11.9189 12.6667 12.6666 13.4143 12.6666 14.3333C12.6666 14.8775 12.4045 15.3614 11.9999 15.6657ZM7.33325 5.66667C7.33325 3.64487 8.97812 2 10.9999 2C13.0217 2 14.6666 3.64487 14.6666 5.66667V8.66667H7.33325V5.66667Z"/></g><defs><clipPath id="clip0_294_906"><rect width="22" height="22"/></clipPath></defs>
                    </svg>
                        
                </label>

            </div>
        </div>

        <div class="form-check" style="margin-left: 5px; margin-bottom: 20px;">
            {{ form.remember(class="form-check-input") }}
            Remember Me
        </div>
        
        <!-- button -->
        <div class="submit-frame" style="position:relative; ">
            {{ form.submit(id="submit", class="button-red-outline", style="width: 100%; max-width: 100%;", type="submit") }}
            {{ form.hidden_tag() }}
            <!--<button style="width: 100%; max-width: 100%;" class="button-red-outline" type="submit"><span>Send message</span></button>-->
        </div>

        <div class="form-login-bottom">
            <small class="text-muted ml-2"> <!-- TODO replace classes-->
                <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
            </small>

            <small class="lighter-text"> <!-- TODO replace classes-->
                Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign up now</a> <!-- TODO replace classes-->
            </small>
        </div>

        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="flask-alert flask-alert-{{ category }}"> <!-- TODO replace classes-->
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

    </form>
</div>


{% endblock %}

website/templates/portfolio_element.html

{% include "portfolio.html" %}
<div class="container container-top">
    <div class="nav-pos-holder"></div>
    <div class="content">
        <div class="section portfolio-element-selected" >
            <h2 class="section-title">{{ PortfolioElementSelected.name }}</h2>
            
            {% if PortfolioElementSelected.type == "project" %}
                {% if PortfolioElementSelected.github_link %}
                    <a class="view-more-secondary" href="{{ PortfolioElementSelected.github_link }}">
                        <p>View more on Github</p>  
                        <svg class="icon" style="width: 15px; height: 15px; margin-top: 3px;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 300"><defs><style>.view-more1{fill:none;}</style></defs><title>link</title><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><rect class="view-more1" width="300" height="300"/><path d="M24.23,15.5C17.87,15.52,12.5,27,12.5,27V278A11.5,11.5,0,0,0,24,289.5H275.37a11.5,11.5,0,0,0,11.5-11.5V153.65c0-5.38-4.32-10.7-9.63-11.55a11.55,11.55,0,0,0-13.54,11.33V266.7h-228v-228h113.1A11.72,11.72,0,0,0,160.27,27a11.52,11.52,0,0,0-11.5-11.52Zm182.42,0a11.59,11.59,0,0,0,0,23.17H247.3l-88.92,88.94A11.58,11.58,0,0,0,174.76,144L263.7,55V95.73a11.59,11.59,0,0,0,23.17,0V27a11.5,11.5,0,0,0-11.5-11.5Z"/></g></g></svg>  
                    </a>
                {% endif %}
            {% endif %}

            <br>

            <!-- images -->
            <div class="portfolio-element-selected-images-section" >
                <div class="portfolio-element-selected-images-top">
                    <div class="portfolio-element-selected-images-arrow-left">
                        <svg style="fill: none;" width="18" height="33" viewBox="0 0 18 33" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M16 2L3 17.3735L16 31" stroke="#DEDEDE" stroke-width="3" stroke-linecap="round"/>
                        </svg>    
                    </div>
                    <div class="portfolio-element-selected-images">
                        <!-- Duplicate last image -->
                        <img class="port-elem-sel-image" src="{{ url_for('static', filename=OrderedImages[-1].image_path) }}" alt="portofolio element image">
                        
                        {% for image in OrderedImages %}
                            <a data-fancybox="gallery"  href="{{ url_for('static', filename=image.image_path) }}">
                                <img class="port-elem-sel-image" data-index="{{ loop.index0 }}" src="{{ url_for('static', filename=image.image_path) }}" alt="portofolio element image">
                            </a>
                        {% endfor %}
                        
                        <!-- Duplicate first image -->
                        <img class="port-elem-sel-image" src="{{ url_for('static', filename=OrderedImages[0].image_path) }}" alt="portofolio element image">
                    </div>
                    <div  class="portfolio-element-selected-images-arrow-right">
                        <svg  style="fill: none;"  width="18" height="33" viewBox="0 0 18 33" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M2 2L15 17.3735L2 31" stroke="#DEDEDE" stroke-width="3" stroke-linecap="round"/>
                        </svg>
                    </div>
                </div>
                <div class="portfolio-element-selected-images-bottom">
                    <div class="portfolio-element-selected-secondary-arrow-left">
                        <svg style="fill: none;" width="18" height="33" viewBox="0 0 18 33" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M16 2L3 17.3735L16 31" stroke="#DEDEDE" stroke-width="3" stroke-linecap="round"/>
                        </svg>
                    </div>
                    <div class="image-lines">
                        {% for image in PortfolioElementSelected.images %}
                            <div class="image-line"></div>
                        {% endfor %}
                    </div>
                    <div class="portfolio-element-selected-secondary-arrow-right">
                        <svg  style="fill: none;"  width="18" height="33" viewBox="0 0 18 33" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M2 2L15 17.3735L2 31" stroke="#DEDEDE" stroke-width="3" stroke-linecap="round"/>
                        </svg>
                    </div>
                </div>
            </div>

            <div class="portfolio-element-selected-content">
                <div class="portfolio-element-selected-left">
                    <div class="portfolio-element-selected-block-left" >
                        <div class="portfolio-element-selected-description">
                            <p>{{ PortfolioElementSelected.description }}</p>
                        </div>
                        <div class="portfolio-element-selected-tags">
                            {% for tag in PortfolioElementSelected.tags %}
                                <div class="tag-big tag-big-{{ tag.name }}">
                                    {{ SvgContents[tag.name]|safe }}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="portfolio-element-selected-right">
                    <div class="portfolio-element-selected-block-right" >
                        <div class="portfolio-element-selected-comments-top">
                            <!--show number of comments-->
                            <p>{{ PortfolioElementSelected.comments|length }} Comments</p>
                            {% if not current_user.is_authenticated %}
                                <span><a href="{{ url_for('users.login', next=request.url) }}">Login</a> / <a href="{{ url_for('users.register', next=request.url) }}">Sign up</a>
                            {% endif %}
                            </span>
                        </div>
                        <div class="portfolio-element-selected-comments">
                            <div class="portfolio-element-selected-comments-add">
                                <div>
                                    {% if current_user.is_authenticated %}
                                        <img class="comment-image" src=" {{ url_for('static', filename='images/users/profile_pics/' + current_user.image_file) }} " alt="portofolio element image">
                                    {% else %}
                                        <img class="comment-image" src=" {{ url_for('static', filename='images/users/profile_pics/default.jpg') }} " alt="portofolio element image">
                                    {% endif %}
                                    
                                </div>
                                <div class="portfolio-element-selected-comments-formblock">
                                    <form action="" method="POST">
                                        {{ form.content(id="portfolio-comment-content", class="p-e-s-comment-add-input", placeholder="Add a comment ...", required="") }}
                                        {% if current_user.is_authenticated %}
                                            {{ form.submit(id="p-e-s-comment-add-submit",  class="p-e-s-comment-add-submit", type="submit", value="Comment") }}
                                        {% else %}
                                            <p>To comment please login or sign up</p>
                                        {% endif %}
                                        {{ form.hidden_tag() }}
                                    </form>
                                </div>
                            </div>
                            <div class="portfolio-element-selected-comments-elements">
                
                                <!-- Dynamicly add comments of PortfolioElementSelected--> 
                                {% for comment in PortfolioElementSelected.comments %}
                                    <div class="portfolio-element-selected-comment">
                                        <div class="comment-image-block">
                                            <img class="comment-image" src="{{ url_for('static', filename='images/users/profile_pics/' + comment.author_object.image_file) }}" alt="portofolio element image">
                                        </div>
                                        <div class="portfolio-element-selected-comment-text">
                                            <!--if it is current youser just write You-->
                                            {% if comment.author_object == current_user %}
                                                <h3><b>You</b></h3>
                                            {% else %}
                                                <h3>{{ comment.author_object.username }}</h3>
                                            {% endif %}
                                            <p>{{ comment.content }}</p>        
                                        </div>
                                    </div>
                                {% endfor %}

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="portfolio-element-selected-bottom">
                <p>{{ PortfolioElementSelected.date_text }}</p>
                        <!-- View more link -->
                        {% if PortfolioElementSelected.type == "project" %}
                            {% if PortfolioElementSelected.github_link %}
                                <a class="view-more" href="{{ PortfolioElementSelected.github_link }}">
                                    <p>View more on Github</p>  
                                    <svg class="icon" style="width: 20px; height: 20px;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 300"><defs><style>.view-more1{fill:none;}</style></defs><title>link</title><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><rect class="view-more1" width="300" height="300"/><path d="M24.23,15.5C17.87,15.52,12.5,27,12.5,27V278A11.5,11.5,0,0,0,24,289.5H275.37a11.5,11.5,0,0,0,11.5-11.5V153.65c0-5.38-4.32-10.7-9.63-11.55a11.55,11.55,0,0,0-13.54,11.33V266.7h-228v-228h113.1A11.72,11.72,0,0,0,160.27,27a11.52,11.52,0,0,0-11.5-11.52Zm182.42,0a11.59,11.59,0,0,0,0,23.17H247.3l-88.92,88.94A11.58,11.58,0,0,0,174.76,144L263.7,55V95.73a11.59,11.59,0,0,0,23.17,0V27a11.5,11.5,0,0,0-11.5-11.5Z"/></g></g></svg>  
                                </a>
                            {% endif %}
                        {% endif %}
            </div>
            
        </div>
    </div>
</div>


<!-- Script for portfolio element that darken the background and redirect to portfolio page if clicked-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{{ url_for('static', filename='plugins/fancybox.min.js') }}"></script>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='plugins/fancybox.min.css') }}" media="all" onload="this.media='all'">
<noscript><link rel="stylesheet" href="{{ url_for('static', filename='plugins/fancybox.min.css') }}"></noscript>
<script>
$(document).ready(function() {
    $('.content').addClass('portfolio-element-active');

    $('.content').click(function(event) {
        if (event.target === this) {
            window.location.href = "/portfolio{% if request.query_string.decode() %}?{{ request.query_string.decode()|safe }}{% endif %}";
        }
    });

     // Initially set the active class to first
    var middleIndex = Math.floor($('.image-line').length / 2);
    $('.image-line').eq(middleIndex).addClass('active');
    //give active to first line
    //$('.image-line').eq(0).addClass('active');
});
</script>
 <!-- import portfolio-element.js -->
 <script src="{{ url_for('static', filename='javascript/portfolio-element.js') }}"></script>
 

website/templates/reset_token.html
{% extends "layout.html" %}
   
{% block content %}
    <div class="section section-form" id="registration" style="padding-top: 15px;">
        <h2 class="section-title" style="margin-bottom: 15px; font-size: 30px;">Change password</h2> <!-- TODO change from intag styling to main.css-->
        <form id="form" class="general-form" method="POST">

            <div class="form-field" style="position:relative;">
                <!-- password input -->
                <div>
                    {% if form.password.errors %}
                        {{ form.password(id='password', class='input is-invalid', placeholder='Password', required='') }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(id='password', class='input', placeholder='Password', required='') }}
                    {% endif %} 
                    <label for="password">
    
                        <svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <g clip-path="url(#clip0_294_906)"><path d="M4.33325 22H17.6666C18.2189 22 18.6666 21.5523 18.6666 21V9.66667C18.6666 9.1144 18.2189 8.66667 17.6666 8.66667H16.6666V5.66667C16.6666 2.54207 14.1245 0 10.9999 0C7.87532 0 5.33325 2.54207 5.33325 5.66667V8.66667H4.33325C3.78099 8.66667 3.33325 9.1144 3.33325 9.66667V21C3.33325 21.5523 3.78099 22 4.33325 22ZM11.9999 15.6657V17C11.9999 17.5523 11.5522 18 10.9999 18C10.4477 18 9.99992 17.5523 9.99992 17V15.6657C9.59539 15.3614 9.33325 14.8775 9.33325 14.3333C9.33325 13.4143 10.0809 12.6667 10.9999 12.6667C11.9189 12.6667 12.6666 13.4143 12.6666 14.3333C12.6666 14.8775 12.4045 15.3614 11.9999 15.6657ZM7.33325 5.66667C7.33325 3.64487 8.97812 2 10.9999 2C13.0217 2 14.6666 3.64487 14.6666 5.66667V8.66667H7.33325V5.66667Z" fill="#DEDEDE"/></g><defs><clipPath id="clip0_294_906"><rect width="22" height="22"/></clipPath></defs>
                        </svg>
                            
                    </label>
    
                </div>
            </div>
    
            <div class="form-field" style="position:relative;">
                <!-- confirm password input -->
                <div>
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(id='confirm_password', class='input is-invalid', placeholder='Confirm password', required='') }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(id='confirm_password', class='input', placeholder='Confirm password', required='') }}
                    {% endif %} 
                    <label for="confirm_password">
    
                        <svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <g clip-path="url(#clip0_294_906)"><path d="M4.33325 22H17.6666C18.2189 22 18.6666 21.5523 18.6666 21V9.66667C18.6666 9.1144 18.2189 8.66667 17.6666 8.66667H16.6666V5.66667C16.6666 2.54207 14.1245 0 10.9999 0C7.87532 0 5.33325 2.54207 5.33325 5.66667V8.66667H4.33325C3.78099 8.66667 3.33325 9.1144 3.33325 9.66667V21C3.33325 21.5523 3.78099 22 4.33325 22ZM11.9999 15.6657V17C11.9999 17.5523 11.5522 18 10.9999 18C10.4477 18 9.99992 17.5523 9.99992 17V15.6657C9.59539 15.3614 9.33325 14.8775 9.33325 14.3333C9.33325 13.4143 10.0809 12.6667 10.9999 12.6667C11.9189 12.6667 12.6666 13.4143 12.6666 14.3333C12.6666 14.8775 12.4045 15.3614 11.9999 15.6657ZM7.33325 5.66667C7.33325 3.64487 8.97812 2 10.9999 2C13.0217 2 14.6666 3.64487 14.6666 5.66667V8.66667H7.33325V5.66667Z" fill="#DEDEDE"/></g><defs><clipPath id="clip0_294_906"><rect width="22" height="22"/></clipPath></defs>
                        </svg>
                            
                    </label>
    
                </div>
            </div>

            <div class="submit-frame" style="position:relative; ">
                {{ form.submit(id="submit", class="button-red-outline", style="width: 100%; max-width: 100%;", type="submit") }}
                {{ form.hidden_tag() }}
                <!--<button style="width: 100%; max-width: 100%;" class="button-red-outline" type="submit"><span>Send message</span></button>-->
            </div>

        </form>
    </div>
{% endblock %}

website/templates/scripts.html

<!-- Local scripts -->

<!-- import nav-line.js for animation of navigation choosing-->
<script src="{{ url_for('static', filename='javascript/nav-line.js') }}"></script>
<!-- import theme-toggle.js for changing themes-->
<script src="{{ url_for('static', filename='javascript/theme-toggle.js') }}"></script>
<!-- import form-validation for showing valid or invalid data in form input-->
<script src="{{ url_for('static', filename='javascript/form-validation.js') }}"></script>
<!-- import filter-buttons for filtering projects and class chosen behavior-->
<script src="{{ url_for('static', filename='javascript/filter-buttons.js') }}"></script>
<!-- import main.js for all other javascript-->
<script src="{{ url_for('static', filename='javascript/main.js') }}"></script>


<!-- plugin scripts -->
<!-- moved mostly to the specific websites because of performance-->